### PR TITLE
I/O examples for the Zynq

### PR DESCRIPTION
**Pull request by violatingcp**
Here are a few I/O examples tested and validated on the Zynq 7020. The one exception is the axistream where the algorithm was tested and validatd with a different hw function. I am in the process of validating the axistream now, will update if anything changes.

### CODE REVIEW

**Comment by nhanvtran** [comment]
can you add READMEs for the vivado and sdk folders?

**Comment by violatingcp** [comment]
READMEs are updated. Also I added some small fixes. The board is connected now. I will keep it connected.

**Comment by nhanvtran** [comment]
hey @violatingcp , i tried the example for bram and got this error at the vivado step

screen shot 2017-11-02 at 11 12 43 pm

**Comment by nhanvtran** [comment]
Ok, working now!

**Pull request merged**
